name: {name}

on:
  push:
    branches:    
      - main

jobs:
  inform_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Send POST request
      uses: actions/http-request@v2
      with:
        url: 'https://example.com/api/endpoint'
        method: 'POST'
        headers: '{"Content-Type": "application/json"}'
        data: '{"key": "value"}'
